"""autogenerated by genpy from BP/Detections.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import BP.msg

class Detections(genpy.Message):
  _md5sum = "ca05d6b60fdc98a12a77e103e579b06f"
  _type = "BP/Detections"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 BALL=0      # Ball detection
int32 OTHERS=1    # Other objects detection
int32 type
BP/PointOfInterest[] ballcenters

================================================================================
MSG: BP/PointOfInterest
float64 x
float64 y

"""
  # Pseudo-constants
  BALL = 0
  OTHERS = 1

  __slots__ = ['type','ballcenters']
  _slot_types = ['int32','BP/PointOfInterest[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       type,ballcenters

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Detections, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.type is None:
        self.type = 0
      if self.ballcenters is None:
        self.ballcenters = []
    else:
      self.type = 0
      self.ballcenters = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_struct_i.pack(self.type))
      length = len(self.ballcenters)
      buff.write(_struct_I.pack(length))
      for val1 in self.ballcenters:
        _x = val1
        buff.write(_struct_2d.pack(_x.x, _x.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.ballcenters is None:
        self.ballcenters = None
      end = 0
      start = end
      end += 4
      (self.type,) = _struct_i.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ballcenters = []
      for i in range(0, length):
        val1 = BP.msg.PointOfInterest()
        _x = val1
        start = end
        end += 16
        (_x.x, _x.y,) = _struct_2d.unpack(str[start:end])
        self.ballcenters.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_struct_i.pack(self.type))
      length = len(self.ballcenters)
      buff.write(_struct_I.pack(length))
      for val1 in self.ballcenters:
        _x = val1
        buff.write(_struct_2d.pack(_x.x, _x.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.ballcenters is None:
        self.ballcenters = None
      end = 0
      start = end
      end += 4
      (self.type,) = _struct_i.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ballcenters = []
      for i in range(0, length):
        val1 = BP.msg.PointOfInterest()
        _x = val1
        start = end
        end += 16
        (_x.x, _x.y,) = _struct_2d.unpack(str[start:end])
        self.ballcenters.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_i = struct.Struct("<i")
_struct_2d = struct.Struct("<2d")
