preset_objects:

 -
  name: box1
  x: [0.75, 1.25, 1.25, 0.75]
  y: [0.25, -0.25, -0.25, 0.25]
  intensity: 101.0
 -
  name: polygon
  x: [0.3, 0.4, 0.5, 0.5, 0.4]
  y: [-0.3, -0.4, -0.3, -0.2, -0.2]
  intensity: 101.0
