preset_objects:

 -
  name: box
  x: [-0.9, -0.5, -0.5, -0.9]
  y: [1.15, 1.15, 1.55, 1.55]
  intensity: 101.0
 -
  name: triangle
  x: [-1.65, -1.25, -1.45]
  y: [ 1.55, 1.55, 1.15]
  intensity: 101.0
 -
  name: 6hran
  x: [-2.5, -2.1, -1.9, -2.1, -2.5, -2.7]
  y: [ 1.0,  1.0,  1.2,  1.4,  1.4,  1.2]
  intensity: 101.0
