/* Auto-generated by genmsg_cpp for file /home/dprokopo/rosbuild_ws/sandbox/BP/msg/PointOfInterest.msg */
#ifndef BP_MESSAGE_POINTOFINTEREST_H
#define BP_MESSAGE_POINTOFINTEREST_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace BP
{
template <class ContainerAllocator>
struct PointOfInterest_ {
  typedef PointOfInterest_<ContainerAllocator> Type;

  PointOfInterest_()
  : x(0.0)
  , y(0.0)
  {
  }

  PointOfInterest_(const ContainerAllocator& _alloc)
  : x(0.0)
  , y(0.0)
  {
  }

  typedef double _x_type;
  double x;

  typedef double _y_type;
  double y;


  typedef boost::shared_ptr< ::BP::PointOfInterest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::BP::PointOfInterest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct PointOfInterest
typedef  ::BP::PointOfInterest_<std::allocator<void> > PointOfInterest;

typedef boost::shared_ptr< ::BP::PointOfInterest> PointOfInterestPtr;
typedef boost::shared_ptr< ::BP::PointOfInterest const> PointOfInterestConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::BP::PointOfInterest_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::BP::PointOfInterest_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace BP

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::BP::PointOfInterest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::BP::PointOfInterest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::BP::PointOfInterest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "209f516d3eb691f0663e25cb750d67c1";
  }

  static const char* value(const  ::BP::PointOfInterest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x209f516d3eb691f0ULL;
  static const uint64_t static_value2 = 0x663e25cb750d67c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::BP::PointOfInterest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "BP/PointOfInterest";
  }

  static const char* value(const  ::BP::PointOfInterest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::BP::PointOfInterest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 x\n\
float64 y\n\
\n\
";
  }

  static const char* value(const  ::BP::PointOfInterest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::BP::PointOfInterest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::BP::PointOfInterest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PointOfInterest_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::BP::PointOfInterest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::BP::PointOfInterest_<ContainerAllocator> & v) 
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
  }
};


} // namespace message_operations
} // namespace ros

#endif // BP_MESSAGE_POINTOFINTEREST_H

